FROM wordpress:4

RUN docker-php-ext-install mysql

ENV WORDPRESS_VERSION 3.7.5
ENV WORDPRESS_UPSTREAM_VERSION 3.7.5
ENV WORDPRESS_SHA1 b2c762558c9688532fe465b7916ba65039015599

# upstream tarballs include ./wordpress/ so this gives us /usr/src/wordpress
RUN curl -o wordpress.tar.gz -sSL https://wordpress.org/wordpress-${WORDPRESS_UPSTREAM_VERSION}.tar.gz \
  && echo "$WORDPRESS_SHA1 *wordpress.tar.gz" | sha1sum -c - \
  && tar -xzf wordpress.tar.gz -C /usr/src/ \
  && rm wordpress.tar.gz

ENTRYPOINT ["/entrypoint.sh"]
CMD ["apache2-foreground"]
