FROM wordpress:4

ENV WORDPRESS_VERSION 3.9.3
ENV WORDPRESS_UPSTREAM_VERSION 3.9.3
ENV WORDPRESS_SHA1 77c150646b732587a5acbe9daf3b164901dba991

# upstream tarballs include ./wordpress/ so this gives us /usr/src/wordpress
RUN curl -o wordpress.tar.gz -sSL https://wordpress.org/wordpress-${WORDPRESS_UPSTREAM_VERSION}.tar.gz \
  && echo "$WORDPRESS_SHA1 *wordpress.tar.gz" | sha1sum -c - \
  && tar -xzf wordpress.tar.gz -C /usr/src/ \
  && rm wordpress.tar.gz

ENTRYPOINT ["/entrypoint.sh"]
CMD ["apache2-foreground"]
