FROM wordpress:4

ENV WORDPRESS_VERSION 4.0.1
ENV WORDPRESS_UPSTREAM_VERSION 4.0.1
ENV WORDPRESS_SHA1 ef1bd7ca90b67e6d8f46dc2e2a78c0ec4c2afb40

# upstream tarballs include ./wordpress/ so this gives us /usr/src/wordpress
RUN curl -o wordpress.tar.gz -sSL https://wordpress.org/wordpress-${WORDPRESS_UPSTREAM_VERSION}.tar.gz \
  && echo "$WORDPRESS_SHA1 *wordpress.tar.gz" | sha1sum -c - \
  && tar -xzf wordpress.tar.gz -C /usr/src/ \
  && rm wordpress.tar.gz

ENTRYPOINT ["/entrypoint.sh"]
CMD ["apache2-foreground"]
