services:
  tinify-mock-api:
    image: tinify-mock-api
    build:
      context: ..
      dockerfile: ./config/Dockerfile-mock-webservice
    ports:
      - '8100:80'
    volumes:
      - ../test/mock-tinypng-webservice:/var/www/html
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - tinify

networks:
  tinify:
    external: true